CREATE INDEX IDX_TASK_PSL_1 ON PROC_SCHEDULE_LOG (queue_flag, valid_flag);
CREATE INDEX IDX_TASK_PSL_2 ON PROC_SCHEDULE_LOG (task_state, valid_flag);
CREATE INDEX IDX_TASK_PSL_3 ON PROC_SCHEDULE_LOG (SEQNO);
CREATE INDEX IDX_TASK_PSL_4 ON PROC_SCHEDULE_LOG (XMLID);

CREATE INDEX IDX_TASK_TP_1 ON TRANSDATAMAP_DESIGN (TRANSNAME);
CREATE INDEX IDX_TASK_PSSL_1 ON PROC_SCHEDULE_SOURCE_LOG (SEQNO,check_flag);
CREATE INDEX IDX_TASK_PSSL_2 ON PROC_SCHEDULE_SOURCE_LOG (SEQNO,source);
CREATE INDEX IDX_TASK_PSSCL_1 ON PROC_SCHEDULE_SCRIPT_LOG (SEQNO);

CREATE INDEX IDX_TASK_PSML_1 ON PROC_SCHEDULE_META_LOG (TARGET, DATA_TIME);
CREATE INDEX IDX_TASK_PSML_2 ON PROC_SCHEDULE_META_LOG (proc_name, date_args);

CREATE INDEX IDX_TASK_PSTL_1 ON proc_schedule_target_log (trigger_flag);

CREATE INDEX IDX_TASK_PSR_1 ON proc_schedule_runpara (xmlid);

CREATE INDEX IDX_TASK_RUNINDEX_1 ON proc_schedule_run_index (index_type,MONTH_ID);